import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
import Script from "next/script";
export const metadata = {
  title: "DHA GUJRANWALA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
              <Navbar />
              {children}
              <Footer />
              <Script
                src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"
              />
              <Script src="https://cdn.lordicon.com/lordicon.js"/>
            </body>
          </html>
          );
}
